### ISSUE TITLE
Invalid depends

### ISSUE THREAD

**Issue by demmm** [KaOS-Community-Packages/ranger#1]
There is no package "python" in KaOS
Follow the guidelines for submitting to KCP, add url in README.

**Comment by bvaudour** [comment]
Plus, no need to keep optdepends which are not in repos neither in kcp.

**Comment by ShalokShalom** [comment]
I keep the optdepends, because its easy for others to see then, which are available:
They can package by themself then.
Fixed

**Comment by abveritas** [comment]
README is for added messages, not opdepends, remove line with not available
packages.

Send from my Nexus

**Comment by ShalokShalom** [comment]
Ok, write it into the Readme
